---
- hosts: all
  become: true
  tasks:

   - name: install apache and php on nodes
     package:
      update-cache: yes
      name: install docker
       - "{{ apache_package }}"
         "{{ php_package }}"
         "{{ docker_package }}"
      state: latest 
